Resources:
    CognitoUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            AdminCreateUserConfig:
                AllowAdminCreateUserOnly: false
                UnusedAccountValidityDays: 30
            AutoVerifiedAttributes:
                - email
            UsernameAttributes:
                - email
            EmailVerificationMessage: 'Welcome to IAWSHI?verify_code={####}'
            EmailVerificationSubject: 'Welcome to CHILLNN'
            LambdaConfig:
                CustomMessage: 'arn:aws:lambda:ap-northeast-1:070977098101:function:dev-host-cognito-controller'
            MfaConfiguration: 'OFF'
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
                    RequireLowercase: true
                    RequireNumbers: true
                    RequireSymbols: true
                    RequireUppercase: true
            UserPoolName: ${self:custom.stage}-CognitoUserPool

    CognitoUserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            ClientName: ${self:custom.stage}-CognitoUserPoolClientTatsuya
            GenerateSecret: false
            ExplicitAuthFlows:
                - 'ADMIN_NO_SRP_AUTH'
            ReadAttributes:
                - 'email'
            RefreshTokenValidity: 30
            UserPoolId:
                Ref: CognitoUserPool
            WriteAttributes:
                - 'email'

Outputs:
    UserPoolId:
        Value:
            Ref: CognitoUserPool
        Export:
            Name: ${self:custom.stage}-UserPoolId

    UserPoolClientId:
        Value:
            Ref: CognitoUserPoolClient
        Export:
            Name: ${self:custom.stage}-UserPoolClientId
