Resources:
    # IAM role used for authenticated users
    CognitoUserAuthRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: chillnn-identityPool-host-authorizedRole
            Path: /
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: 'Allow'
                      Principal:
                          Federated: 'cognito-identity.amazonaws.com'
                      Action:
                          - 'sts:AssumeRoleWithWebIdentity'
                      Condition:
                          StringEquals:
                              'cognito-identity.amazonaws.com:aud':
                                  Ref: CognitoUserIdentityPool
                          'ForAnyValue:StringLike':
                              'cognito-identity.amazonaws.com:amr': authenticated
            Policies:
                - PolicyName: 'CognitoAuthorizedPolicy'
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: 'Allow'
                            Action:
                                - 'mobileanalytics:PutEvents'
                                - 'cognito-sync:*'
                                - 'cognito-identity:*'
                            Resource: '*'
                          - Effect: 'Allow'
                            Action:
                                - 'execute-api:Invoke'
                            Resource:
                                - '*'
                          - Action:
                                - s3:GetObject
                                - s3:PutObject
                                - s3:DeleteObject
                            Resource:
                                - arn:aws:s3:::iwashimidnight1011/public/*
                                - Fn::Join: ['', ['arn:aws:s3:::iwashimidnight1011/protected/$', '{cognito-identity.amazonaws.com:sub}/*']]
                                - Fn::Join: ['', ['arn:aws:s3:::iwashimidnight1011/private/$', '{cognito-identity.amazonaws.com:sub}/*']]
                            Effect: Allow
                          - Action:
                                - s3:PutObject
                            Resource:
                                - arn:aws:s3:::iwashimidnight1011/uploads/*
                            Effect: Allow
                          - Action:
                                - s3:GetObject
                            Resource:
                                - arn:aws:s3:::iwashimidnight1011/protected/*
                            Effect: Allow
                          - Condition:
                                StringLike:
                                    s3:prefix:
                                        - public/
                                        - public/*
                                        - protected/
                                        - protected/*
                                        - Fn::Join: ['', ['private/$', '{cognito-identity.amazonaws.com:sub}/']]
                                        - Fn::Join: ['', ['private/$', '{cognito-identity.amazonaws.com:sub}/*']]
                            Action:
                                - s3:ListBucket
                            Resource:
                                - arn:aws:s3:::iwashimidnight1011
                            Effect: Allow
